name: CI

on:
  push:
    branches:
      - master

jobs:
  build-linux:
    name: linux
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Installing V
      run: (cd /tmp && git clone --depth=1 https://github.com/vlang/v && make -C v && sudo ln -fs $PWD/v/v /usr/bin/v)
    - name: Format test
      run: v fmt main.v filelock/*.v
    - name: Running example
      run: v run main.v
    - name: Windows build
      run: v -os windows main.v && ls -l main.exe
